version: "2.2"
services:
  jobmanager:
    image: pyflink
    network_mode: host
    volumes:
    - ./:/home/pyflink
    ports:
      - "8089:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 5000M
  taskmanager:
    image: pyflink
    network_mode: host
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    deploy:
      resources:
        limits:
          cpus: '2'    
          memory: 5000M
