proxy:
  image:
    repository: proxy
    tag: latest
    pullPolicy: IfNotPresent
  flink_operator_ServiceAccount: flink-operator
  affinity: {}
  tolerations: {}
  extraEnv: 
    BASIC_USERNAME: flink
    BACKEND_BASE_URL: http://localhost:8000  ## USED in NODEJS APP
  extraSecretEnv:
    BASIC_PASSWORD: ChangeMe
  
    
