apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http-backend
    port: 3001
