apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "backend"
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccount: {{ .Values.backend.flink_operator_ServiceAccount }}
      serviceAccountName: {{ .Values.backend.flink_operator_ServiceAccount }}
      containers:
      - name: app
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: 3001
        {{- if .Values.backend.extraEnv }}
        env:
          {{- range $key, $value := .Values.backend.extraEnv }}
          - name: {{ $key | quote}}
            value: {{ $value | quote }}
          {{- end }}
        {{- end }}
        envFrom:
          - secretRef:
              name: backend-secret
        command:
        - /bin/sh
        - -c
        - node app.js
      {{- if .Values.backend.affinity }}
      affinity: {{ .Values.backend.affinity }}
      {{- end }}
      {{- if .Values.backend.tolerations }}
      tolerations: {{ .Values.backend.tolerations }}
      {{- end }}