apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-proxy
  name: nginx-proxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nginx-proxy"
  template:
    metadata:
      labels:
        app: nginx-proxy
      annotations:
        checksum/nginx_config: {{ .Values.proxy.nginx_config | toYaml | sha256sum }}
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
      containers:
      - name: nginx-proxy
        image: {{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}
        imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
        ports:
        - containerPort: 80
        {{- if .Values.proxy.extraEnv }}
        env:
          {{- range $key, $value := .Values.proxy.extraEnv }}
          - name: {{ $key | quote}}
            value: {{ $value | quote }}
          {{- end }}
        {{- end }}
        volumeMounts:
        - name: nginx-conf
          mountPath: /nginx-basic-auth.conf
          subPath: nginx-basic-auth.conf
        envFrom:
          - secretRef:
              name: proxy-secret
        command:
        - /bin/sh
        - -c
        - |
          apt-get update -y && apt-get install -y apache2-utils 
          envsubst < nginx-basic-auth.conf > /etc/nginx/conf.d/default.conf
          htpasswd -c -b /etc/nginx/.htpasswd $BASIC_USERNAME $BASIC_PASSWORD
          nginx -g "daemon off;"  
      {{- if .Values.proxy.affinity }}
      affinity: {{ .Values.proxy.affinity }}
      {{- end }}
      {{- if .Values.proxy.tolerations }}
      tolerations: {{ .Values.proxy.tolerations }}
      {{- end }}