apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy-svc
  name: proxy-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: nginx-proxy
  ports:
  - name: http-nginxproxy
    port: 80
