apiVersion: v1
kind: Secret
metadata:
  name: proxy-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
    {{- if .Values.proxy.extraSecretEnv }}
    {{- range $key, $value := .Values.proxy.extraSecretEnv }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}

